### ISSUE TITLE
Use GCM for authenticated encryption

### ISSUE THREAD

**Issue by glkz** [domodwyer/cryptic#4]
Go `crypto/cipher` package supports [GCM authenticated encryption](https://golang.org/pkg/crypto/cipher/#NewGCM) mode. It would be better to use this instead of current custom schema.

**Comment by domodwyer** [comment]
Hi @glkz, 
Thanks for taking the time to read through the code, it's a good call. I'm away for conferences with work at the moment but it's something I can add after I get back. 

If you have the time I'll happily accept a PR, if not it's something in the pipeline.

Dom

**Comment by domodwyer** [comment]
This is something I plan on adding soon, just need to make the time!
